version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/usr/src/app'
    ports:
      - "5008:5000"
    environment:
      # FLASK_APP: manage.py
      FLASK_DEBUG: 1
      FLASK_ENV: development
      APP_SETTINGS: src.config.DevelopmentConfig
      DATABASE_URL: postgresql://postgres:postgres@db:5432/demo_db 
    depends_on:
      - db
    networks:
      - app-network 

  db:
    image: postgres:latest
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: demo_db
    ports:
      - "5433:5432"
    networks:
      - app-network

networks:
  app-network:  
